default:
  tags:
    - moodle

stages:
  - preflight
  - test
  - deploy

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - when: always

include:
  - component: $CI_SERVER_FQDN/amc/moodle/moodle-ci/moodle-plugin-ci@5.0
  - component: $CI_SERVER_FQDN/amc/moodle/moodle-ci/moodle-devil-app@5.0

validate:
  variables:
    MUSTACHE_IGNORE_NAMES: 'formstart.mustache,formend.mustache'
    PHPMD_EXCLUDE_PATHS: 'category.php,create_element.php,classes/importhandler.php,classes/plugininfo.php,db/install.php'
    MOODLE_PLUGIN_CI_PHPMD_EXCLUDE: 'category.php,create_element.php,classes/importhandler.php,classes/plugininfo.php,db/install.php'
