// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * TinyMCE styles plugin for Moodle.
 *
 * @ package tiny_styles
 * @author Karri Pajarinen
 * @copyright Academic Moodle Cooperation {@link http://www.academic-moodle-cooperation.org}
 * @license http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

import {getTinyMCE} from 'editor_tiny/loader';
import {getPluginMetadata} from 'editor_tiny/utils';
import {pluginName} from './common';
import {register as registerOptions} from './options';
import {getSetup as getCommandSetup} from './commands';
import {editCustomStyles} from './commands';
import * as Configuration from './configuration';

/**
 * Injects a self-contained FA Solid stylesheet into the editor iframe for FA icons to render.
 *
 * The CSS file is generated by tools/generate_fa_icons.js and must be regenerated
 * when Moodle upgrades its bundled Font Awesome version.
 *
 * @param {Object} editor - The TinyMCE editor instance
 */
const injectFontAwesome = (editor) => {
    try {
        const doc = editor.getDoc();
        if (!doc || !doc.head) {
            return;
        }
        const linkId = 'tiny-styles-injected-fa';
        if (doc.getElementById(linkId)) {
            return;
        }
        const link = doc.createElement('link');
        link.id = linkId;
        link.rel = 'stylesheet';
        link.href = M.cfg.wwwroot
            + '/lib/editor/tiny/plugins/styles/css/editor_fa.css?rev='
            + (M.cfg.themerev || 1);
        doc.head.appendChild(link);
    } catch (e) {
        // Silent.
    }
};

/**
 * Injects Bootstrap styles bundled with the plugin into the editor iframe.
 * This makes sure that the predefined elements render properly.
 *
 * Direct DOM manipulation with appending a link element to iframe head.
 *
 * @param {Object} editor - The tinyMCE editor
 */
const injectEditorStyles = (editor) => {
    try {
        // Get iframe.
        const doc = editor.getDoc();
        if (!doc || !doc.head) {
            return;
        }

        const cssLinkId = 'tiny-styles-injected-css';

        if (doc.getElementById(cssLinkId)) {
            return;
        }

        // Config file path.
        // The 'themerev'' parameter busts browser cache when Moodle caches are purged to force css style updates.
        const pluginCssUrl = M.cfg.wwwroot + '/lib/editor/tiny/plugins/styles/css/styles.css?rev=' + (M.cfg.themerev || 1);

        // Link to iframe head with unique ID.
        const link = doc.createElement('link');
        link.id = cssLinkId;
        link.rel = 'stylesheet';
        link.href = pluginCssUrl;
        doc.head.appendChild(link);

    } catch (e) {
        // Silent.
    }
};


// eslint-disable-next-line no-async-promise-executor
export default new Promise(async(resolve) => {
    try {
        const [
            tinyMCE,
            pluginMetadata,
            setupCommands] = await Promise.all([
            getTinyMCE(),
            getPluginMetadata(pluginName, pluginName),
            getCommandSetup(),
        ]);

        // Register the plugin
        tinyMCE.PluginManager.add(pluginName, (editor) => {
            registerOptions(editor);
            setupCommands(editor);

            editor.on('init', async() => {
                injectEditorStyles(editor);
                injectFontAwesome(editor);
                // Runs a check on the editor text to update custom in text styles.
                await editCustomStyles(editor);
            });
            return pluginMetadata;
        });
        // Load panel and icon styles into the outer page.
        const menuStyleLink = document.createElement('link');
        menuStyleLink.rel = 'stylesheet';
        menuStyleLink.href = M.cfg.wwwroot
            + '/lib/editor/tiny/plugins/styles/css/menu.css?rev='
            + (M.cfg.themerev || 1);
        document.head.appendChild(menuStyleLink);

        resolve([pluginName, Configuration]);

    } catch (error) {
        // Console.error('Error initializing TinyMCE plugin:', error);
    }
});
